In [1]:
#import numpy as np

#### 1. Two Sum

In [2]:
def two_sum(input: list, target: int) -> list:
    for i in range(len(input)):
        for j in range(i+1, len(input)):
                if input[i] + input[j] == target:
                    return [i, j]
    
    print("No solution found. Should not be possible!")
    return None

print(two_sum([2,7,11,15], 9) == [0, 1])
print(two_sum([3,2,4], 6) == [1, 2])
print(two_sum([3,3], 6) == [0, 1])

True
True
True


#### 2. Add Two Numbers

In [3]:
def add_two_numbers(l1, l2):
    n1 = len(l1)
    n2 = len(l2)
    
    if n1 > n2:
        l2 = l2 + [0] * (n1-n2)
    elif n1 > n2:
        l1 = l1 + [0] * (n2-n1)

    l = []
    r = 0
    for i in range(n1):
        s = l1[i] + l2[i] + r
        if s >= 10:
            r = 1
            s = s-10
        else:
            r = 0
        l.append(s)

    if r > 0:
        l.append(r)

    return l

print(add_two_numbers([2,4,3], [5,6,4]) == [7, 0, 8])
print(add_two_numbers([0], [0]) == [0])
print(add_two_numbers([9,9,9,9,9,9,9], [9,9,9,9]) == [8,9,9,9,0,0,0,1])

True
True
True


#### 3. Longest Substring Without Repeating Characters
Given a string, find the length of the longest substring without repeating characters.

In [4]:
def longest_substring(s):
    n = len(s)
    for i in range(n, 0, -1):
        for j in range(0, n-i+1):
            si = list(s[j:j+i])
            if len(list(set(si))) == len(si):
                return len(si)

print(longest_substring("abcabcbb") == 3)
print(longest_substring("bbbbb") == 1)
print(longest_substring("pwwkew") == 3)

True
True
True


#### 4. Median of Two Sorted Arrays
Given two sorted arrays num1 and num2 of size m and n respectively, return the median of the two sorted arrays.

In [5]:
# Currently not a O(log(n+m)) solution
def median_of_two_sorted_arrays(num1, num2):
    num = sorted(num1 + num2)
    n = len(num)//2
    if len(num)%2 == 0:
        return (num[n-1] + num[n])/2
    else:
        return num[n]

print(median_of_two_sorted_arrays([1,3], [2]) == 2)
print(median_of_two_sorted_arrays([1,2], [3,4]) == 2.5)

True
True


#### 5. Longest Palindromic Substring
Given a string, return the longest Palindromic substring in s. A string is Palindromic if it reads the same forwards and backwards, i.e. "kook".

In [6]:
def longest_palindromic_substring(s):
    n = len(s)
    m = 0
    while not n == 0:
        for i in range(m):
            ss = s[i:i+n]
            if ss == ss[::-1]:
                return ss

        n -= 1
        m += 1

    return None

print(longest_palindromic_substring("babad") == "bab")
print(longest_palindromic_substring("cbbd") == "bb")

True
True


#### 6. Zigzag Conversion
The string PAYPALISHIRING is written in a zigzag pattern on a given number of rows like this:
P   A   H   N
A P L S I I G
Y   I   R
and then read line by line: PAHNAPLSIIGYIR

Write the code that will take a string and make this conversion given a number of rows.

In [51]:
def zigzag_conversion(s: str, n: int):
    if n == 1:
        return s
    elif n == 2:
        return s[0:len(s):2] + s[1:len(s):2]
    else:
        # Expand
        if len(s)%n != 0:
            s += " " * (n - len(s)%n)

        snew = []
        i = 0
        while i < len(s):

            d = i%(n-1)
            if d == 0:
                snew.append(s[i:i+n])
                i += n
            else:
                b = n-d-1
                snew.append((" " * b) + s[i:i+1] + (" " * d))
                i += 1

        snew2 = ""
        for i in range(n):
            for j in range(len(snew)):
                snew2 += snew[j][i]

        snew2 = snew2.replace(" ", "")
        
        return snew2

print(zigzag_conversion("PAYPALISHIRING", 3) == "PAHNAPLSIIGYIR")
print(zigzag_conversion("PAYPALISHIRING", 4) == "PINALSIGYAHRPI")
print(zigzag_conversion("A", 1) == "A")


True
True
True


#### 7. Reverse Integer
Given a signed 32-bit integer, x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 -1], then return 0.

In [81]:
def reverse_integer(x):
    if not isinstance(x, int):
        raise TypeError("The argument 'x' must be an integer")

    if x < 0:
        s = -1
    else:
        s = 1
    
    x = str(abs(x))
    x = ''.join(list(reversed(list(x))))
    x = int(x)*s

    num = 2**31
    if x < -num or x > (num-1):
        return 0

    return x

print(reverse_integer(123) == 321)
print(reverse_integer(-123) == -321)
print(reverse_integer(120) == 21)
print(reverse_integer(2**40) == 0)

True
True
True
True


#### 8. String to Integer (atoi)
Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer.

In [89]:
def string_to_integer(s):

    # 1. Whitespace
    s = s.strip()

    # 2. Signedness
    sig = 1
    if s[0] == "-":
        sig = -1
        s = s[1:]
    elif s[0] == "+":
        s = s[1:]

    # 3. Conversion
    x = "0"
    for i in range(len(s)):
        if s[i] in ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]:
            x += s[i]
        else:
            break

    x = int(x)

    # 4. Rounding
    num = 2**31
    if x < -num or x > (num-1):
        x = 0

    return x*sig

print(string_to_integer("42") == 42)
print(string_to_integer(" -042") == -42)
print(string_to_integer("1337c0d3") == 1337)
print(string_to_integer("0-1") == 0)
print(string_to_integer("words and 987") == 0)

True
True
True
True
True


#### Problem 48. Rotate Image

In [8]:
A1 = np.arange(9).reshape(3,3) + 1
A2 = np.array([5, 1, 9, 11, 2, 4, 8, 10, 13, 3, 6, 7, 15, 14, 12, 16]).reshape(4, 4)

NameError: name 'np' is not defined

In [ ]:
def rotate90(A):
    if not A.ndim == 2:
        ValueError("The input 'A' must be a 2-dimensional array")
    nrow, ncol = A.shape
    if not nrow == ncol:
        ValueError("The matrix 'A' must be square")

    n = nrow // 2
    for i in range(n):
        c1 = A[i, i:ncol-i-1]
        c2 = A[i:ncol-i-1, ncol-1]
        c3 = A[nrow-i-1, i+1:ncol-i]
        c4 = A[i+1:nrow, i]

        print("C1", c1)
        print("C2", c2)
        print("C3", c3)
        print("C4", c4)

        A[i, i:ncol-i-1] = c4
        A[i:ncol-i-1, ncol-1] = c1
        A[nrow-i-1, i+1:ncol-i] = c2
        A[i+1:nrow, i] = c3

    return A


#print(A2)
print(rotate90(A1))

C1 [1 2]
C2 [3 6]
C3 [8 9]
C4 [4 7]
[[4 7 4]
 [4 5 7]
 [7 4 7]]


In [ ]:
A1

array([[4, 7, 4],
       [4, 5, 7],
       [7, 4, 7]])